name: line_animator
description: A Line Animator for Flutter
version: 1.0.0+1
repository: https://github.com/ibrierley/line_animator
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.8.0
  #cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

